name: E2E (server-root, scripts/, robust wait)

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
  workflow_dispatch: {}

jobs:
  e2e:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:7
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })' || exit 1"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 20

    env:
      NODE_ENV: development
      PORT: 3000
      MONGODB_URI: mongodb://127.0.0.1:27017/yubiwait_ci
      INTERNAL_TOKEN: ci-internal-token
      AUTO_CALLER_INTERVAL_MS: "1000"
      STORE_ID: "687e4062912938dd2558db4f"
      BASE_URL: http://127.0.0.1:3000/api

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Show layout (for debug)
        run: |
          pwd
          ls -la
          ls -la scripts || true

      - name: Install dependencies
        run: npm ci

      - name: Seed CI data (Store)
        run: node scripts/seed_ci.js

      - name: Start server (background)
        run: |
          nohup node index.js > server.log 2>&1 & echo $! > server.pid
          sleep 1
          echo "Server PID: $(cat server.pid)"

      - name: Wait for server (ready:true up to 120s)
        shell: bash
        run: |
          for i in {1..120}; do
            body="$(curl -fsS http://127.0.0.1:3000/api/ping || true)"
            echo "[$i/120] ping => $body"
            if echo "$body" | grep -q '"ready":true'; then
              echo "Server is ready ✅"
              exit 0
            fi
            sleep 1
          done
          echo "::error::Server did not report ready:true in time"
          echo "=== server.log (tail) ==="
          tail -n 200 server.log || true
          exit 1

      - name: Run E2E - cancel
        run: node scripts/cancel_e2e.js

      - name: Run E2E - autocaller
        run: node scripts/autocaller_e2e.js

      - name: Run E2E - near
        run: node scripts/near_e2e.js

      - name: Run E2E - ready
        run: node scripts/ready_e2e.js

      - name: Run E2E - staff
        run: node scripts/staff_e2e.js

      - name: Show server.log on failure
        if: failure()
        run: |
          echo "=== server.log ==="
          cat server.log || true
